### ISSUE TITLE
Matrix-vector products -- special case for A = sparse, B = dense with shape (N, 1)

### ISSUE THREAD

**Issue by tbenthompson** [flatironinstitute/sparse_dot#1]
This is a great project! Thanks very much!

One suggestion is to add a special case for matrix-vector products. I'm seeing a decent speedup (4sec vs 6sec) in a microbenchmark by switching from using this sparse_dot package to just calling `mkl_sparse_d_mv` directly.

**Comment by asistradition** [comment]
Seems reasonable. Implemented through dot_product_mkl in 4562745f4ad1f6db4b79b3b776881b30cd7fbaa7 with the same behavior as np.dot - returns (N,) when B is 1d, (N, 1) when B is 2d. Will write tests for it and package it at some point this week.

**Comment by tbenthompson** [comment]
Awesome! Thanks!

**Comment by asistradition** [comment]
Packaged and released as v0.4.0; if there are any problems feel free to reopen.

**Comment by asistradition** [comment]
It was pointed out to me that basically one more line of code and vector (dot) matrix would work too; implemented in 8a929c2fcbdd370f2872f1d927dca7544df26208 and released as v0.4.1
