### ISSUE TITLE
MKL internal representation for BSR

### ISSUE THREAD

**Issue by gnool** [flatironinstitute/sparse_dot#10]
First of all, thank you all for the really awesome work here.

What does it take to support BSR format?

**Comment by asistradition** [comment]
I don't think there should be any problem supporting BSR. There used to be a couple of MKL functions that didn't work with BSR, but I think most of those have been resolved in 2020. I'll give it a shot and see how it goes.

**Comment by gnool** [comment]
@asistradition Thanks, looking forward to that. I had a quick try yesterday and for my particular problem at hand which involves blocked sub-matrices (block size roughly 100), BSR really offers the best speed when it comes to matrix-vector multiplication as compared to CSC/CSR formats. Also it beats Scipy's Cython implementation by an order of magnitude.

**Comment by gnool** [comment]
@asistradition actually would be eager to try your implementation. The one I've implemented seems to be bugged, can't find out the part where I did wrongly, but half of my output array of matrix-vector operation seems to be filled with zeros ...

**Comment by gnool** [comment]
Never mind me regarding the bug mentioned above, I was too careless with int32 vs int64

**Comment by asistradition** [comment]
Aight I have a working implementation for BSR 48db2b430d333831188304b79328d3bf6b8e75d1

The BSR matrix must have a square block size, and only BSR (dot) BSR works - MKL doesn't support BSR multiplied against anything else. BSR against a dense vector is fine though. Also, I'm not getting the right results out of sparse_syrk when I give it a BSR, and I'm not sure why yet.

I'm going to write some more tests and try to fix whatever's wrong with sparse_syrk before I package this. 

Also unless it's changed recently I'm fairly sure that scipy has only directly implemented CSR-vector multiplication and just quietly converts any other format to CSR internally.

**Comment by asistradition** [comment]
Aight I think I got everything - I couldn't figure out why `mkl_sparse_syrk` doesn't give correct results so `gram_matrix_mkl` doesn't support BSR matrices. The dot product function should be fine though.

I packaged everything and released it as v0.7.0

**Comment by gnool** [comment]
Any plan to report this to Intel?

**Comment by asistradition** [comment]
Not currently. I'd need a working example of the problem written in C before I could be confident it's an MKL problem and not an error with the python wrapper. It's also a function that's a bit redundant - you can get the same result from just calling `mkl_sparse_spmm` (`syrk` is just modestly faster because it's specialized).
