### ISSUE TITLE
Problems on calling mkl_sparse_z_trsm.

### ISSUE THREAD

**Issue by bentrainer** [flatironinstitute/sparse_dot#27]
Hi, I want to test the performance of `mkl_sparse_z_trsm` which isn't in this package, I tried to add a new function but got some error. I would be thankful if anyone is willing to help to take a look🙏:
https://gist.github.com/bentrainer/ca6a75b39ac3b645423ee767fe2d5307#file-solve_mkl-py

What I want to achieve in the code is:
1. Do the Cholesky decomposition of a sparse matrix $A=LL^H=R^HR$ where $L$ and $R$ are triangular matrix (lower and upper).
2. Call `mkl_sparse_z_trsm` twice to solve $Ax=b$ from $x=L^H\backslash L\backslash b=R\backslash R^H\backslash b$.

Then I got two problems:
1. I have to explicitly convert `b = b.astype(MKL_Complex16)` from `np.complex128`, or else it will throw `TypeError: array must have data type {'names': ['real', 'imag'], 'formats': ['<f8', '<f8'], 'offsets': [0, 8], 'itemsize': 16, 'aligned': True}`, is this expected behavior when dealing with complex array?
3. After converting, I still got `OSError: exception: access violation reading`. I may did something wrong, because I want `mkl_sparse_z_trsm` to simply overwrite the `b` matrix and I did not allocate a new array but simply copied `cb = b.copy()` and throw it in the MKL function.

**Comment by asistradition** [comment]
np.complex128 is identical in array form to MKL_Complex16, so you don't have to cast into that type (MKL_Complex16 is defined so that it can be used for scalars, because python's native complex can't be).

I would suggest that you fix the argtypes as follows:
```
from sparse_dot_mkl._mkl_interface import MKL

mkl_sparse_z_trsm.argtypes = [
    _ctypes.c_int,
    MKL_Complex16,
    sparse_matrix_t,
    matrix_descr,
    _ctypes.c_int,
    ndpointer(dtype=np.cdouble, ndim=2),
    MKL.MKL_INT,
    MKL.MKL_INT,
    ndpointer(dtype=np.cdouble, ndim=2),
    MKL.MKL_INT,
]
mkl_sparse_z_trsm.restypes = _ctypes.c_int
```
This function will not overwrite `cb`, it will add to the existing `cb`, so you can't pass b in as both x and y. You should pass `b` in for x and `cb` in for y if that is what you want to do.

**Comment by bentrainer** [comment]
Thanks for your advice, it looks clearer now, also I found that if I use column major layout for `b` with `SPARSE_LAYOUT_COLUMN_MAJOR` configuration it won't give `access violation reading` now. Though it still gives `SPARSE_STATUS_NOT_SUPPORTED` error but I'll check what's going wrong later when I have time.

**Comment by asistradition** [comment]
Change SPARSE_LAYOUT_COLUMN_MAJOR to row major - that's the layout parameter that corresponds to the dense array order, not the sparse array structure

**Comment by bentrainer** [comment]
Yeah, they don't support `SPARSE_LAYOUT_COLUMN_MAJOR` and I should use row major instead which complies numpy's default.
Fun fact is that function is still single threaded, and if I try `mkl_sparse_set_sm_hint` will result in `SPARSE_STATUS_NOT_SUPPORTED` again. Sigh.
